name: Deploy to ECR

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 805809698730.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY_FASTAPI: newsapp-fastapi
  ECR_REPOSITORY_NGINX: newsapp-nginx

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS $ECR_REGISTRY

      - name: Build and push FastAPI image
        run: |
          docker build -t $ECR_REPOSITORY_FASTAPI:latest -f Dockerfile .
          docker tag $ECR_REPOSITORY_FASTAPI:latest $ECR_REGISTRY/$ECR_REPOSITORY_FASTAPI:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FASTAPI:latest

      - name: Build and push Nginx image
        run: |
          docker build -t $ECR_REPOSITORY_NGINX:latest -f nginx/Dockerfile ./nginx
          docker tag $ECR_REPOSITORY_NGINX:latest $ECR_REGISTRY/$ECR_REPOSITORY_NGINX:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NGINX:latest
